folder_path: "C:/Users/User/Desktop/Coding"
output_path: "C:/Users/User/Desktop/Coding/EchoSnip/found_snippets.txt"
debug_log_path: "C:/Users/User/Desktop/Coding/EchoSnip/debug_log.txt"
debug: true

languages:
  Python:
    extensions:
      - ".py"
    block_type: "indentation"
    identifier: "**%"
    comment_start: "#"

  C++:
    extensions:
      - ".cpp"
      - ".hpp"
      - ".h"
    block_type: "brace"
    identifier: "**%"
    comment_start: "//"

  CSS:
    extensions:
      - ".css"
    block_type: "brace"
    identifier: "**%"
    comment_start: "/*"
    comment_end: "*/"

  HTML:
    extensions:
      - ".html"
      - ".htm"
    block_type: "html_tag"
    identifier: "**%"
    comment_start: "<!--"
    comment_end: "-->"

  Javascript:
    extensions:
      - ".js"
    block_type: "brace"
    identifier: "**%"
    comment_start: "//"